image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  policy: pull-push
  paths:
    - .m2/repository
    - .gradle/caches
    - .allure

build:
  stage: build
  script: ./gradlew compileTestJava
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  script: ./gradlew test
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  artifacts:
    paths:
      - build/allure-results

pages:
  stage: deploy
  dependencies:
    - test
  script:
    - ./gradlew allureReport
    - mv build/reports/allure-report/ public/
  artifacts:
    paths:
      - public

