name: Allure Reports with history

on:
  push:
    branches-ignore:
      - '!master' # ignore gh-pages
    #paths-ignore:
    #- 'docs/**'

#env:
#  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:
  autotests:
    name: Generate Allure Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: |
            ~/.m2/repository
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install dependencies
        run: ./gradlew compileTestJava

      - name: Run Test
        if: always()
        run: ./gradlew test
        continue-on-error: true

      - name: Composite Allure Action
        uses: ./allure-history-action
        if: always()
        with:
          allure_results: build/allure-results
          #allure_report: allure-report
          branch: gh-pages

#      - name: Get Allure history
#        uses: actions/checkout@v2
#        if: always()
#        continue-on-error: true
#        with:
#          ref: gh-pages
#          path: gh-pages
#
#      - name: Allure Report action from marketplace
#        uses: simple-elf/allure-report-action@v1.1
#        if: always()
#        #id: allure-report
#        with:
#          allure_results: build/allure-results
#          #gh_pages: gh-pages
#          #allure_report: allure-report
#          allure_history: allure-history
#
#      - name: Deploy report to Github Pages
#        if: always()
#        uses: peaceiris/actions-gh-pages@v2
#        env:
#          PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#          PUBLISH_BRANCH: gh-pages
#          PUBLISH_DIR: allure-history

      #- uses: actions/upload-artifact@master
      #  with:
      #    name: allure-history
      #    path: allure-history